name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        if: github.ref == 'refs/heads/master'
        run: |
          sudo snap install hub --classic
          hub --help
      - name: Check out STACH SDKs
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
      - name: Check out STACH model
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
      - name: Contents
        if: github.ref == 'refs/heads/master'
        run: |
          ls -latr
          ls -latr /stachschema-models
      - name: Build the Docker image and test
        if: github.ref != 'refs/heads/master'
        run: |
          docker build --build-arg VERSION=4.2.2 -t openapi-generator-cli-custom -f Dockerfile .
          docker images
          docker run --rm -v "${PWD}:/local" openapi-generator-cli-custom generate --generator-name CustomPythonClientCodegen --input-spec https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml --output /local/out --skip-validate-spec
          
