name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        if: github.ref == 'refs/heads/master'
        run: |
          sudo snap install hub --classic
          hub --help
      - name: Check out STACH SDKs
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
          token: ${{ secrets.USER_API_KEY }}
      - name: Check out STACH model
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
          ref: ${{ github.ref }}
      - name: Running docker
        if: github.ref == 'refs/heads/master'
        run: |
          export STACH_MODELS_PATH=${PWD}/stachschema-models/proto
          export STACH_SDKS_REPO_PATH=${PWD}/stachschema-sdks
          docker-compose -f stachschema-sdks/docker-compose.yml up
      - name: Check for diff
        if: github.ref == 'refs/heads/master'
        run: |
          if git -C stachschema-sdks diff-index --quiet HEAD; then 
            echo "No changes to the STACH models"; 
          else 
            echo "Detected changes in STACH models";
            export STACH_CHANGES=1;
            echo "::set-env name=STACH_CHANGES::$STACH_CHANGES";
          fi
      - name: Master and raise pull request
        if: github.ref == 'refs/heads/master' && env.STACH_CHANGES == 1
        run: |
          printenv
          git config --global user.email "saigiridhar21@gmail.com"
          git config --global user.name "saigiridhar21"
          export GITHUB_USER=${{ env.GITHUB_ACTOR }}
          export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
          cd stachschema-sdks
          git checkout -b test_branch
          git status
          git add -A .
          echo "Helloo1"
          git commit -m "feat(stachschema-sdks): Updating SDKs";
          echo "Helloo2"
          git push origin test_branch;
          hub --help
          echo "Helloo3"
          hub pull-request -b test_branch
      - name: Build the Docker image and test
        if: github.ref != 'refs/heads/master'
        run: |
          docker build --build-arg VERSION=4.2.2 -t openapi-generator-cli-custom -f Dockerfile .
          docker images
          docker run --rm -v "${PWD}:/local" openapi-generator-cli-custom generate --generator-name CustomPythonClientCodegen --input-spec https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml --output /local/out --skip-validate-spec
          
