name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: |
          sudo snap install hub --classic
      - name: Check out STACH SDKs
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
          token: ${{ secrets.USER_API_KEY }}
      - name: Check out STACH model
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
          fetch-depth: 0
      - name: Check whether models were changed in last commit
        run: |
          git -C stachschema-models log -1 --stat --oneline --no-decorate
          t=`git -C stachschema-models log -1 --stat --oneline --no-decorate`
          echo $t
          count=`git -C stachschema-models log -1 --stat --oneline --no-decorate | grep -c ".proto$"`
          echo $count
          if [ "$count" -eq "0" ]; then
            echo "No STACH models were updated"
          else
            echo "( $count ) STACH models were updated. Updating the STACH SDKs"
            export STACH_CHANGES=1;
            echo "::set-env name=STACH_CHANGES::$STACH_CHANGES";
          fi       
      - name: Updating the SDK code locally
        if: env.STACH_CHANGES == 1
        run: |
          export STACH_MODELS_PATH=${PWD}/stachschema-models/proto
          export STACH_SDKS_REPO_PATH=${PWD}/stachschema-sdks
          docker-compose -f stachschema-sdks/docker-compose.yml up
      - name: Master and raise pull request
        if: env.STACH_CHANGES == 1
        run: |
          cd stachschema-sdks
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"
          
          branch_name="feat/stachschema_sdks_`date +%s`/updating-models" 
          git checkout -b $branch_name
          git status
          git add -A .
          git commit -m "feat(stachschema-sdks): Updating SDKs";
          echo "Committed all the changes"
          
          git push origin $branch_name
          echo "Pushed all the changes to remote location"
          
          export GITHUB_USER=${{ secrets.USER }}
          export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
          hub pull-request -m "feat(stachschema-sdks): Updating SDKs" -h $branch_name
