name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: |
          sudo snap install hub --classic
      - name: Check out STACH SDKs
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
          token: ${{ secrets.USER_API_KEY }}
      - name: Check out STACH model
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
      - name: Check whether models were changed in last commit
        run: |
          count=`git -c stachschema-models log -1 --stat --oneline --no-decorate | grep -c .proto`
          if $count -eq 0; then
            echo "No STACH models were updated"
            return false
          else
            echo "( $count ) STACH models were updated. Updating the STACH SDKs"
            export STACH_CHANGES=1;
            echo "::set-env name=STACH_CHANGES::$STACH_CHANGES";
          fi       
      - name: Updating the SDK code locally
        if: env.STACH_CHANGES == 1
        run: |
          export STACH_MODELS_PATH=${PWD}/stachschema-models/proto
          export STACH_SDKS_REPO_PATH=${PWD}/stachschema-sdks
          docker-compose -f stachschema-sdks/docker-compose.yml up
      - name: Master and raise pull request
        if: env.STACH_CHANGES == 1
        run: |
          printenv
          git config --global user.email "saigiridhar21@gmail.com"
          git config --global user.name "saigiridhar21"
          export GITHUB_USER=${{ env.GITHUB_ACTOR }}
          export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
          cd stachschema-sdks
          git checkout -b test_branch
          git status
          git add -A .
          echo "Helloo1"
          git commit -m "feat(stachschema-sdks): Updating SDKs";
          echo "Helloo2"
          hub --help
          hub push origin test_branch;
          echo "Helloo3"
          hub pull-request -m "$(git log -1 --pretty=%B)" -h test_branch
