name: Generate STACH SDKs and raise the pull request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: |
          sudo snap install hub --classic
          
      - name: Check out STACH models
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
          fetch-depth: 0
          ref: "${{ github.head_ref }}" 
          
      - name: Check branch
        run: |
          cd stachschema-models
          git status
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.actor }}"
          echo "${{ github.event.number }}"
          echo "${{ toJson(github) }}"
          
      - name: Check whether models were changed in last commit
        run: |
          count=`git -C stachschema-models log -1 --name-only --oneline | grep -E ".*\.proto$" | wc -l`
          if [ "$count" -eq "0" ]; then
            echo "No STACH models were updated"
          else
            echo "( $count ) STACH models were updated. Updating the STACH SDKs"
            export STACH_CHANGES=1;
            echo "::set-env name=STACH_CHANGES::$STACH_CHANGES";
          fi  
          
      - name: Check out STACH SDKs
        if: env.STACH_CHANGES == 1
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
          token: ${{ secrets.USER_API_KEY }}
          fetch-depth: 0
          
      - name: Set GitHub configs
        run: |
          cd stachschema-sdks
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"
                   
      - name: Cloning existing branch if yes
        if: env.STACH_CHANGES == 1
        run: |
          cd stachschema-sdks
          
          export STACH_MODELS_PATH=${PWD}/../stachschema-models/proto
          export STACH_SDKS_REPO_PATH=${PWD}
          docker-compose -f docker-compose.generate.yml up
                   
      - name: Create Pull Request
        if: env.STACH_CHANGES == 1
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.USER_API_KEY }}  
          path: "stachschema-sdks"
          commit-message: "feat(stachschema-sdks): Auto generated commit from the stachschema PR ${{ github.event.number }}"
          committer: GitHub <noreply@github.com>
          author: ${{ secrets.USER }} <${{ secrets.USER_EMAIL }}>
          signoff: false
          branch: "feat/stachschema-sdks/stachschema-pr-${{ github.event.number }}"
          base: "feat/stachschema-sdks/stachschema-pr-${{ github.event.number }}"
          title: "Auto generated PR from the stachschema PR ${{ github.event.number }}"
          body: |
            Auto generated PR from the stachschema PR ${{ github.event.number }}
          labels: |
            stachschema
            sdks
            autogen-pr
          assignees: ${{ github.actor }}
          draft: false

      - name: Create pull request
        if: env.STACH_CHANGES == 2
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.USER_API_KEY }}
        with:
          title: "Auto generated PR from the stachschema PR ${{ github.event.number }}"
          body: "Auto generated PR from the stachschema PR ${{ github.event.number }}"
          branch: "feat/stachschema-sdks/stachschema-pr-${{ github.event.number }}"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          path: "stachschema-sdks/"
          commit-message: "feat(stachschema-sdks): Auto generated commit from the stachschema PR ${{ github.event.number }}"

