name: Generate STACH SDKs and raise the pull request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: |
          sudo snap install hub --classic
          
      - name: Check out STACH models
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-models
          path: stachschema-models
          fetch-depth: 0
          ref: "${{ github.head_ref }}" 
          
      - name: Check branch
        run: |
          cd stachschema-models
          git status
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.actor }}"
          echo "${{ github.event.number }}"
          echo "${{ toJson(github) }}"
          
      - name: Check whether models were changed in last commit
        run: |
          count=`git -C stachschema-models log -1 --name-only --oneline | grep -E ".*\.proto$" | wc -l`
          if [ "$count" -eq "0" ]; then
            echo "No STACH models were updated"
          else
            echo "( $count ) STACH models were updated. Updating the STACH SDKs"
            export STACH_CHANGES=1;
            echo "::set-env name=STACH_CHANGES::$STACH_CHANGES";
          fi  
          
      - name: Check out STACH SDKs
        if: env.STACH_CHANGES == 1
        uses: actions/checkout@v2
        with:
          repository: saigiridhar21/stachschema-sdks
          path: stachschema-sdks
          token: ${{ secrets.USER_API_KEY }}
          fetch-depth: 0
                   
      - name: Cloning existing branch if yes
        if: env.STACH_CHANGES == 1
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"
          
          cd stachschema-sdks
          pr_number="${{ github.event.number }}"
          branch_name="feat/stachschema-sdks/stachschema-pr-$pr_number"
          remote_branch_check=$(git ls-remote --heads origin $branch_name)
          if [ -z "$remote_branch_check" ]
          then
            echo "Does not exist"
            
            git checkout -b $branch_name
                        
            export STACH_MODELS_PATH=${PWD}/../stachschema-models/proto
            export STACH_SDKS_REPO_PATH=${PWD}
            docker-compose -f docker-compose.generate.yml up
            
            git status
            if git diff-index --quiet HEAD -- 
            then 
              echo "No changes to commit." 
            else 
              git add -A .
              git commit -m "feat(sdk): Auto-commit from PR $pr_number for STACH SDK"
              echo "Committed all the changes"
            
              git push origin $branch_name
              echo "Pushed all the changes to remote location"
            fi
            
            export GITHUB_USER=${{ secrets.USER }}
            export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
            hub pull-request -m "feat(stachschema-sdks): Updating SDKs" -h $branch_name
            
          else
            echo "Already exists"
                      
            git checkout $branch_name
            git pull
            
            export STACH_MODELS_PATH=${PWD}/../stachschema-models/proto
            export STACH_SDKS_REPO_PATH=${PWD}
            docker-compose -f docker-compose.generate.yml up
            
            git status
            if git diff-index --quiet HEAD -- 
            then 
              echo "No changes to commit." 
            else 
              git add -A .
              git commit -m "feat(sdk): Auto-commit from PR $pr_number for STACH SDK"
              echo "Committed all the changes"
            
              git push origin $branch_name
              echo "Pushed all the changes to remote location"
            fi
          fi
                   
      - name: Updating SDKs code locally
        if: env.STACH_CHANGES == 2
        run: |
          export STACH_MODELS_PATH=${PWD}/stachschema-models/proto
          export STACH_SDKS_REPO_PATH=${PWD}/stachschema-sdks
          docker-compose -f stachschema-sdks/docker-compose.generate.yml up
          
      - name: Raise pull request
        if: env.STACH_CHANGES == 2
        run: |
          cd stachschema-sdks
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"
          
          branch_name="feat/stachschema_sdks_`date +%s`/updating-models" 
          git checkout -b $branch_name
          git status
          git add -A .
          git commit -m "feat(stachschema-sdks): Updating SDKs";
          echo "Committed all the changes"
          
          git push origin $branch_name
          echo "Pushed all the changes to remote location"
          
          export GITHUB_USER=${{ secrets.USER }}
          export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
          hub pull-request -m "feat(stachschema-sdks): Updating SDKs" -h $branch_name

